spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/sample_db?currentSchema=sample_sc&ssl=false
        username: admin
        password: password

mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath*:/com/example/mybatissample/repository/*.xml
